// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojcjujtjchlntkqupwnl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qY2p1anRqY2hsbnRrcXVwd25sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMDQzOTgsImV4cCI6MjA2ODY4MDM5OH0.tR00pb29cS8BuJhUF3GIXdlJb5HmdWIJCPAqjUmMHPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});